version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend

  backend:
    build: ./backend
    command: gunicorn --workers 1 --bind 0.0.0.0:5001 --timeout 600 app:app
    ports:
      - '5001:5001'
